---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
  - name: pre-run | update package cache (Debian/Ubuntu)
    tags: always
    apt: update_cache=yes
    changed_when: false
    when: ansible_distribution in ["Debian", "Ubuntu"]

  tasks:
  - name: install utilities
    package:
      name:
        - htop
        - curl
        - gimp
        - git-gui
        - meld
        - nodejs
        - npm
        - flameshot
        - jq
        - snapd
        - ffmpeg
        - apt-transport-https
  - name: Install VS Code
    snap:
      name: code
      classic: true
  - name: Download MS product repository
    get_url:
      url: 'https://packages.microsoft.com/config/ubuntu/{{ ansible_distribution_version }}/packages-microsoft-prod.deb'
      dest: /tmp/packages-microsoft-prod.deb
  - name: Install MS product repository
    apt: deb=/tmp/packages-microsoft-prod.deb
  - name: Install .NET Core SDK
    apt:
      name: dotnet-sdk-5.0
      state: present
      update_cache: true
