---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
  - name: pre-run | update package cache (Debian/Ubuntu)
    tags: always
    apt: update_cache=yes
    changed_when: false
    when: ansible_distribution in ["Debian", "Ubuntu"]

  tasks:
  - name: install utilities
    package:
      name:
        - htop
        - curl
        - gimp
        - git-gui
        - meld
        - nodejs
        - npm
        - flameshot
        - jq
        - snapd
        - ffmpeg

