---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
  - name: pre-run | update package cache (Debian/Ubuntu)
    tags: always
    apt: update_cache=yes
    changed_when: false
    when: ansible_distribution in ["Debian", "Ubuntu"]

  tasks:
  - name: install utilities
    package:
      name:
        - htop
        - curl
        - gimp
        - git-gui
        - meld
        - nodejs
        - npm
        - flameshot
        - jq
        - snapd
        - ffmpeg
        - apt-transport-https
  - name: Install VS Code
    snap:
      name: code
      classic: true
  - name: Download MS product repository
    get_url:
      url: 'https://packages.microsoft.com/config/ubuntu/{{ ansible_distribution_version }}/packages-microsoft-prod.deb'
      dest: /tmp/packages-microsoft-prod.deb
  - name: Install MS product repository
    apt: deb=/tmp/packages-microsoft-prod.deb
  - name: Install .NET Core SDK
    apt:
      name: dotnet-sdk-5.0
      state: present
      update_cache: true
  - name: add google public Key
    apt_key:
      id: A040830F7FAC5991
      url: https://dl-ssl.google.com/linux/linux_signing_key.pub
      state: present
  - name: add chrome repository
    apt_repository:
      repo: "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main"
      state: present
      update_cache: true
  - name: install chrome
    apt:
      name: google-chrome-stable
      state: latest
      update_cache: true
      cache_valid_time: 3600
